package converter

import (
	"fmt"
	"os"
	"path/filepath"
)

type ConfigGenerator struct{}

func NewConfigGenerator() *ConfigGenerator {
	return &ConfigGenerator{}
}

func (c *ConfigGenerator) Generate(opts *ConversionOptions) error {
	if err := c.generateServerProperties(opts); err != nil {
		return fmt.Errorf("failed to generate server.properties: %w", err)
	}

	if err := c.generateEULA(opts); err != nil {
		return fmt.Errorf("failed to generate eula.txt: %w", err)
	}

	return nil
}

func (c *ConfigGenerator) generateServerProperties(opts *ConversionOptions) error {
	configPath := filepath.Join(opts.DestDir, "server.properties")

	config := fmt.Sprintf(`#Minecraft server properties
#Generated by Chunk
server-name=%s
motd=%s Server
gamemode=survival
difficulty=normal
allow-flight=false
allow-nether=true
broadcast-console-to-ops=true
broadcast-rcon-to-ops=true
enable-command-block=false
enable-jmx-monitoring=false
enable-query=false
enable-rcon=false
enable-status=true
enforce-whitelist=false
entity-broadcast-range-percentage=100
force-gamemode=false
function-permission-level=2
generate-structures=true
generator-settings={}
hardcore=false
hide-online-players=false
level-name=world
level-seed=
level-type=minecraft\:normal
max-players=20
max-tick-time=60000
max-world-size=29999984
network-compression-threshold=256
online-mode=true
op-permission-level=4
player-idle-timeout=0
prevent-proxy-connections=false
pvp=true
query.port=25565
rate-limit=0
rcon.password=
rcon.port=25575
require-resource-pack=false
resource-pack=
resource-pack-prompt=
resource-pack-sha1=
server-ip=
server-port=25565
simulation-distance=10
spawn-animals=true
spawn-monsters=true
spawn-npcs=true
spawn-protection=16
sync-chunk-writes=true
text-filtering-config=
use-native-transport=true
view-distance=10
white-list=false
`, opts.ModpackName, opts.ModpackName)

	return os.WriteFile(configPath, []byte(config), 0644)
}

func (c *ConfigGenerator) generateEULA(opts *ConversionOptions) error {
	eulaPath := filepath.Join(opts.DestDir, "eula.txt")

	eula := `#By changing the setting below to TRUE you are indicating your agreement to our EULA (https://aka.ms/MinecraftEULA).
#Generated by Chunk
eula=false
`

	return os.WriteFile(eulaPath, []byte(eula), 0644)
}
