package converter

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/alexinslc/chunk/internal/sources"
)

type ScriptGenerator struct{}

func NewScriptGenerator() *ScriptGenerator {
	return &ScriptGenerator{}
}

func (s *ScriptGenerator) Generate(opts *ConversionOptions) error {
	if err := s.generateStartScript(opts); err != nil {
		return fmt.Errorf("failed to generate start script: %w", err)
	}

	if err := s.generateStopScript(opts); err != nil {
		return fmt.Errorf("failed to generate stop script: %w", err)
	}

	return nil
}

func (s *ScriptGenerator) generateStartScript(opts *ConversionOptions) error {
	ramMB := s.calculateRAM(opts)

	var jarFile string
	switch opts.Loader {
	case sources.LoaderForge:
		jarFile = "forge-server.jar"
	case sources.LoaderFabric:
		jarFile = "fabric-server-launch.jar"
	case sources.LoaderNeoForge:
		jarFile = "neoforge-server.jar"
	default:
		jarFile = "server.jar"
	}

	script := fmt.Sprintf(`#!/bin/bash
# Start script for %s
# Generated by Chunk

echo "Starting %s server..."
echo "Minecraft Version: %s"
echo "Loader: %s"
echo "Allocated RAM: %dMB"
echo ""

java -Xms%dM -Xmx%dM -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 \
  -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch \
  -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M \
  -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 \
  -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 \
  -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem \
  -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs \
  -Daikars.new.flags=true \
  -jar %s nogui

echo ""
echo "Server stopped."
`, opts.ModpackName, opts.ModpackName, opts.MCVersion, opts.Loader, ramMB, ramMB/2, ramMB, jarFile)

	scriptPath := filepath.Join(opts.DestDir, "start.sh")
	if err := os.WriteFile(scriptPath, []byte(script), 0755); err != nil {
		return err
	}

	batScript := fmt.Sprintf(`@echo off
REM Start script for %s
REM Generated by Chunk

echo Starting %s server...
echo Minecraft Version: %s
echo Loader: %s
echo Allocated RAM: %dMB
echo.

java -Xms%dM -Xmx%dM -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true -jar %s nogui

echo.
echo Server stopped.
pause
`, opts.ModpackName, opts.ModpackName, opts.MCVersion, opts.Loader, ramMB, ramMB/2, ramMB, jarFile)

	batPath := filepath.Join(opts.DestDir, "start.bat")
	return os.WriteFile(batPath, []byte(batScript), 0755)
}

func (s *ScriptGenerator) generateStopScript(opts *ConversionOptions) error {
	script := `#!/bin/bash
# Stop script for server
# Generated by Chunk

echo "Stopping server..."
screen -S minecraft -X stuff "stop$(printf \\r)"
echo "Stop command sent."
`

	scriptPath := filepath.Join(opts.DestDir, "stop.sh")
	return os.WriteFile(scriptPath, []byte(script), 0755)
}

func (s *ScriptGenerator) calculateRAM(opts *ConversionOptions) int {
	if opts.RecommendedRAM > 0 {
		return opts.RecommendedRAM * 1024
	}

	return 4096
}
